# Generated by Django 5.2.8 on 2025-11-11 19:18

import django.db.models.deletion
from django.db import migrations, models


def asignar_empresas_a_creditos(apps, schema_editor):
    Credito = apps.get_model("creditos", "Credito")
    for credito in Credito.objects.select_related("cliente"):
        credito.empresa_id = credito.cliente.empresa_id
        credito.save(update_fields=["empresa"])


class Migration(migrations.Migration):

    dependencies = [
        ("creditos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credito",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="creditos",
                to="creditos.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="identificacion",
            field=models.CharField(max_length=50, verbose_name="Número de identificación"),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("empresa", "identificacion")},
        ),
        migrations.RunPython(asignar_empresas_a_creditos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="credito",
            name="empresa",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="creditos",
                to="creditos.empresa",
            ),
        ),
    ]
